//! MultiPost 平台目录（与 chatcms-extension/src/shared/platforms.ts 同步）

pub struct CatalogEntry {
    pub code: &'static str,
    pub name: &'static str,
    pub kind: &'static str,
    pub region: &'static str,
    pub inject_url: &'static str,
    pub home_url: &'static str,
}

pub const MULTIPOST_CATALOG: &[CatalogEntry] = &[
    CatalogEntry { code: "DYNAMIC_BILIBILI", name: "哔哩哔哩", kind: "dynamic", region: "cn", inject_url: "https://t.bilibili.com", home_url: "https://t.bilibili.com" },
    CatalogEntry { code: "DYNAMIC_DOUYIN", name: "抖音", kind: "dynamic", region: "cn", inject_url: "https://creator.douyin.com/creator-micro/content/upload?default-tab=3", home_url: "https://creator.douyin.com/" },
    CatalogEntry { code: "DYNAMIC_X", name: "X", kind: "dynamic", region: "intl", inject_url: "https://x.com/home", home_url: "https://x.com/home" },
    CatalogEntry { code: "DYNAMIC_REDNOTE", name: "小红书", kind: "dynamic", region: "cn", inject_url: "https://creator.xiaohongshu.com/publish/publish?target=image", home_url: "https://creator.xiaohongshu.com/" },
    CatalogEntry { code: "DYNAMIC_WEIBO", name: "微博", kind: "dynamic", region: "cn", inject_url: "https://weibo.com", home_url: "https://weibo.com" },
    CatalogEntry { code: "DYNAMIC_XUEQIU", name: "雪球", kind: "dynamic", region: "cn", inject_url: "https://xueqiu.com", home_url: "https://xueqiu.com" },
    CatalogEntry { code: "DYNAMIC_ZHIHU", name: "知乎想法", kind: "dynamic", region: "cn", inject_url: "https://www.zhihu.com", home_url: "https://www.zhihu.com" },
    CatalogEntry { code: "DYNAMIC_INSTAGRAM", name: "Instagram", kind: "dynamic", region: "intl", inject_url: "https://www.instagram.com/", home_url: "https://www.instagram.com/" },
    CatalogEntry { code: "DYNAMIC_FACEBOOK", name: "Facebook", kind: "dynamic", region: "intl", inject_url: "https://www.facebook.com/", home_url: "https://www.facebook.com/" },
    CatalogEntry { code: "DYNAMIC_LINKEDIN", name: "LinkedIn", kind: "dynamic", region: "intl", inject_url: "https://www.linkedin.com/feed", home_url: "https://www.linkedin.com/" },
    CatalogEntry { code: "DYNAMIC_OKJIKE", name: "即刻", kind: "dynamic", region: "cn", inject_url: "https://web.okjike.com", home_url: "https://web.okjike.com" },
    CatalogEntry { code: "DYNAMIC_REDDIT", name: "Reddit", kind: "dynamic", region: "intl", inject_url: "https://www.reddit.com/submit?type=IMAGE", home_url: "https://www.reddit.com/" },
    CatalogEntry { code: "DYNAMIC_PINTEREST", name: "Pinterest", kind: "dynamic", region: "intl", inject_url: "https://www.pinterest.com/pin-creation-tool/", home_url: "https://www.pinterest.com/" },
    CatalogEntry { code: "DYNAMIC_KUAISHOU", name: "快手", kind: "dynamic", region: "cn", inject_url: "https://cp.kuaishou.com/article/publish/video", home_url: "https://cp.kuaishou.com/" },
    CatalogEntry { code: "DYNAMIC_SOHUTV", name: "搜狐视频", kind: "dynamic", region: "cn", inject_url: "https://tv.sohu.com/s/center/", home_url: "https://tv.sohu.com/s/center/" },
    CatalogEntry { code: "DYNAMIC_BAIJIAHAO", name: "百家号动态", kind: "dynamic", region: "cn", inject_url: "https://baijiahao.baidu.com/builder/rc/edit?type=events", home_url: "https://baijiahao.baidu.com/" },
    CatalogEntry { code: "DYNAMIC_TOUTIAO", name: "微头条", kind: "dynamic", region: "cn", inject_url: "https://mp.toutiao.com/profile_v4/weitoutiao/publish", home_url: "https://mp.toutiao.com/" },
    CatalogEntry { code: "DYNAMIC_THREADS", name: "Threads", kind: "dynamic", region: "intl", inject_url: "https://www.threads.net/web", home_url: "https://www.threads.net/web" },
    CatalogEntry { code: "DYNAMIC_WEIXINCHANNEL", name: "视频号动态", kind: "dynamic", region: "cn", inject_url: "https://channels.weixin.qq.com/platform/post/finderNewLifeCreate", home_url: "https://channels.weixin.qq.com/platform" },
    CatalogEntry { code: "DYNAMIC_BLUESKY", name: "Bluesky", kind: "dynamic", region: "intl", inject_url: "https://bsky.app/", home_url: "https://bsky.app/" },
    CatalogEntry { code: "DYNAMIC_V2EX", name: "V2EX", kind: "dynamic", region: "cn", inject_url: "https://www.v2ex.com/write", home_url: "https://www.v2ex.com/" },
    CatalogEntry { code: "DYNAMIC_DOUBAN", name: "豆瓣", kind: "dynamic", region: "cn", inject_url: "https://www.douban.com/", home_url: "https://www.douban.com/" },
    CatalogEntry { code: "DYNAMIC_DEDAO", name: "得到", kind: "dynamic", region: "cn", inject_url: "https://www.dedao.cn/knowledge/home", home_url: "https://www.dedao.cn/" },
    CatalogEntry { code: "DYNAMIC_WEIXIN", name: "公众号动态", kind: "dynamic", region: "cn", inject_url: "https://mp.weixin.qq.com/", home_url: "https://mp.weixin.qq.com/" },
    CatalogEntry { code: "DYNAMIC_WEBHOOK", name: "Webhook", kind: "dynamic", region: "intl", inject_url: "https://multipost.app/about/", home_url: "https://multipost.app/about/" },
    CatalogEntry { code: "DYNAMIC_ZSXQ", name: "知识星球", kind: "dynamic", region: "cn", inject_url: "https://wx.zsxq.com/", home_url: "https://wx.zsxq.com/" },
    CatalogEntry { code: "DYNAMIC_XIAOHEIHE", name: "小黑盒", kind: "dynamic", region: "cn", inject_url: "https://www.xiaoheihe.cn/creator/editor/draft/image_text", home_url: "https://www.xiaoheihe.cn/" },
    CatalogEntry { code: "DYNAMIC_TOUTIAOHAO", name: "头条号动态", kind: "dynamic", region: "cn", inject_url: "https://mp.toutiao.com/profile_v4/weitoutiao/publish", home_url: "https://www.toutiao.com/" },
    CatalogEntry { code: "DYNAMIC_SUBSTACK", name: "Substack", kind: "dynamic", region: "intl", inject_url: "https://substack.com/home", home_url: "https://substack.com/" },
    CatalogEntry { code: "DYNAMIC_MAIMAI", name: "脉脉", kind: "dynamic", region: "cn", inject_url: "https://maimai.cn/community/home/following", home_url: "https://maimai.cn/" },
    CatalogEntry { code: "DYNAMIC_JUEJIN", name: "掘金沸点", kind: "dynamic", region: "cn", inject_url: "https://juejin.cn/pins", home_url: "https://juejin.cn/" },
    CatalogEntry { code: "VIDEO_BILIBILI", name: "哔哩哔哩", kind: "video", region: "cn", inject_url: "https://member.bilibili.com/platform/upload/video/frame", home_url: "https://member.bilibili.com/" },
    CatalogEntry { code: "VIDEO_DOUYIN", name: "抖音", kind: "video", region: "cn", inject_url: "https://creator.douyin.com/creator-micro/content/upload", home_url: "https://creator.douyin.com/" },
    CatalogEntry { code: "VIDEO_YOUTUBE", name: "YouTube", kind: "video", region: "intl", inject_url: "https://studio.youtube.com/", home_url: "https://studio.youtube.com/" },
    CatalogEntry { code: "VIDEO_REDNOTE", name: "小红书", kind: "video", region: "cn", inject_url: "https://creator.xiaohongshu.com/publish/publish?target=video", home_url: "https://creator.xiaohongshu.com" },
    CatalogEntry { code: "VIDEO_TIKTOK", name: "TikTok", kind: "video", region: "intl", inject_url: "https://www.tiktok.com/tiktokstudio/upload", home_url: "https://www.tiktok.com/tiktokstudio" },
    CatalogEntry { code: "VIDEO_WEIXINCHANNEL", name: "视频号", kind: "video", region: "cn", inject_url: "https://channels.weixin.qq.com/platform/post/create", home_url: "https://channels.weixin.qq.com/platform" },
    CatalogEntry { code: "VIDEO_KUAISHOU", name: "快手", kind: "video", region: "cn", inject_url: "https://cp.kuaishou.com/article/publish/video", home_url: "https://cp.kuaishou.com/" },
    CatalogEntry { code: "VIDEO_BAIJIAHAO", name: "百家号", kind: "video", region: "cn", inject_url: "https://baijiahao.baidu.com/builder/rc/edit?type=videoV2", home_url: "https://baijiahao.baidu.com/" },
    CatalogEntry { code: "VIDEO_WEIBO", name: "微博", kind: "video", region: "cn", inject_url: "https://weibo.com/upload/channel", home_url: "https://weibo.com/" },
    CatalogEntry { code: "VIDEO_OKJIKE", name: "即刻", kind: "video", region: "cn", inject_url: "https://web.okjike.com", home_url: "https://web.okjike.com" },
    CatalogEntry { code: "VIDEO_BLUESKY", name: "Bluesky", kind: "video", region: "intl", inject_url: "https://bsky.app/", home_url: "https://bsky.app/" },
    CatalogEntry { code: "VIDEO_ZHIHU", name: "知乎视频", kind: "video", region: "cn", inject_url: "https://www.zhihu.com/zvideo/upload-video", home_url: "https://www.zhihu.com/" },
    CatalogEntry { code: "VIDEO_EASTMONEY", name: "东方财富", kind: "video", region: "cn", inject_url: "https://mp.eastmoney.com/collect/pc_writer/index.html#/publish/video", home_url: "https://www.eastmoney.com/" },
    CatalogEntry { code: "VIDEO_XIAOHEIHE", name: "小黑盒", kind: "video", region: "cn", inject_url: "https://www.xiaoheihe.cn/creator/editor/draft/video", home_url: "https://www.xiaoheihe.cn/" },
    CatalogEntry { code: "VIDEO_TOUTIAOHAO", name: "西瓜视频", kind: "video", region: "cn", inject_url: "https://mp.toutiao.com/profile_v4/xigua/upload-video", home_url: "https://www.toutiao.com/" },
    CatalogEntry { code: "VIDEO_QIE", name: "企鹅号", kind: "video", region: "cn", inject_url: "https://om.qq.com/main/creation/video", home_url: "https://om.qq.com/" },
    CatalogEntry { code: "VIDEO_CHEJIAHAO", name: "车家号", kind: "video", region: "cn", inject_url: "https://creator.autohome.com.cn/web/publish/video", home_url: "https://creator.autohome.com.cn/" },
    CatalogEntry { code: "VIDEO_DEWU", name: "得物", kind: "video", region: "cn", inject_url: "https://creator.dewu.com/release", home_url: "https://creator.dewu.com/" },
    CatalogEntry { code: "VIDEO_YICHE", name: "易车", kind: "video", region: "cn", inject_url: "https://mp.yiche.com/videos/video", home_url: "https://mp.yiche.com/" },
    CatalogEntry { code: "VIDEO_SOHU", name: "搜狐号", kind: "video", region: "cn", inject_url: "https://mp.sohu.com/mpfe/v4/contentManagement/news/addvideo", home_url: "https://mp.sohu.com" },
    CatalogEntry { code: "VIDEO_SOHUTV", name: "搜狐视频", kind: "video", region: "cn", inject_url: "https://tv.sohu.com/s/center/", home_url: "https://tv.sohu.com/s/center/" },
    CatalogEntry { code: "VIDEO_NETEASE", name: "网易号", kind: "video", region: "cn", inject_url: "http://mp.163.com/subscribe_v4/index.html#/home", home_url: "http://mp.163.com/" },
    CatalogEntry { code: "VIDEO_DAYU", name: "大鱼号", kind: "video", region: "cn", inject_url: "https://mp.dayu.com/dashboard/video/write", home_url: "https://mp.dayu.com/" },
    CatalogEntry { code: "VIDEO_ALIPAY", name: "支付宝", kind: "video", region: "cn", inject_url: "https://c.alipay.com/page/content-creation/publish/short-video", home_url: "https://sweb.alipay.com" },
    CatalogEntry { code: "VIDEO_YIDIAN", name: "一点号", kind: "video", region: "cn", inject_url: "https://mp.yidianzixun.com/", home_url: "https://mp.yidianzixun.com/" },
    CatalogEntry { code: "VIDEO_PINDUODUO", name: "拼多多", kind: "video", region: "cn", inject_url: "https://live.pinduoduo.com/creator/live-record", home_url: "https://live.pinduoduo.com/" },
    CatalogEntry { code: "VIDEO_VIVOVIDEO", name: "vivo 短视频", kind: "video", region: "cn", inject_url: "https://kaixinkan.vivo.com.cn/#/home", home_url: "https://kaixinkan.vivo.com.cn/" },
    CatalogEntry { code: "VIDEO_IQIYI", name: "爱奇艺", kind: "video", region: "cn", inject_url: "https://mp.iqiyi.com/sns/publishv2/video", home_url: "https://mp.iqiyi.com/" },
    CatalogEntry { code: "VIDEO_YOUKU", name: "优酷", kind: "video", region: "cn", inject_url: "https://mp.youku.com/v2/manage/upload", home_url: "https://mp.youku.com/" },
    CatalogEntry { code: "VIDEO_TENCENTVIDEO", name: "腾讯视频", kind: "video", region: "cn", inject_url: "https://cm.v.qq.com/upload", home_url: "https://v.qq.com/" },
    CatalogEntry { code: "ARTICLE_CNBLOGS", name: "博客园", kind: "article", region: "cn", inject_url: "https://i.cnblogs.com/articles/edit", home_url: "https://i.cnblogs.com/articles/edit" },
    CatalogEntry { code: "ARTICLE_CSDN", name: "CSDN", kind: "article", region: "cn", inject_url: "https://mp.csdn.net/mp_blog/creation/editor", home_url: "https://mp.csdn.net/mp_blog/creation/editor" },
    CatalogEntry { code: "ARTICLE_ZHIHU", name: "知乎文章", kind: "article", region: "cn", inject_url: "https://zhuanlan.zhihu.com/write", home_url: "https://zhuanlan.zhihu.com/write" },
    CatalogEntry { code: "ARTICLE_JUEJIN", name: "掘金文章", kind: "article", region: "cn", inject_url: "https://juejin.cn/editor/drafts/new?v=2", home_url: "https://juejin.cn/editor/drafts/new?v=2" },
    CatalogEntry { code: "ARTICLE_JIANSHU", name: "简书", kind: "article", region: "cn", inject_url: "https://www.jianshu.com/writer", home_url: "https://www.jianshu.com/writer" },
    CatalogEntry { code: "ARTICLE_SEGMENTFAULT", name: "SegmentFault", kind: "article", region: "cn", inject_url: "https://segmentfault.com/write", home_url: "https://segmentfault.com/write" },
    CatalogEntry { code: "ARTICLE_ALIYUN", name: "阿里云开发者", kind: "article", region: "cn", inject_url: "https://developer.aliyun.com/article/new", home_url: "https://developer.aliyun.com/" },
    CatalogEntry { code: "ARTICLE_TENCENTYUN", name: "腾讯云开发者", kind: "article", region: "cn", inject_url: "https://cloud.tencent.com/developer/article/write-new", home_url: "https://cloud.tencent.com/developer" },
    CatalogEntry { code: "ARTICLE_VOLCENGINE", name: "火山引擎", kind: "article", region: "cn", inject_url: "https://developer.volcengine.com/articles/draft", home_url: "https://developer.volcengine.com/" },
    CatalogEntry { code: "ARTICLE_BAIJIAHAO", name: "百家号", kind: "article", region: "cn", inject_url: "https://baijiahao.baidu.com/builder/rc/edit?type=news", home_url: "https://baijiahao.baidu.com/" },
    CatalogEntry { code: "ARTICLE_TOUTIAO", name: "头条号文章", kind: "article", region: "cn", inject_url: "https://mp.toutiao.com/profile_v4/graphic/publish", home_url: "https://mp.toutiao.com/" },
    CatalogEntry { code: "ARTICLE_QQ", name: "企鹅号", kind: "article", region: "cn", inject_url: "https://om.qq.com/main/creation/article", home_url: "https://om.qq.com/" },
    CatalogEntry { code: "ARTICLE_DOUBAN", name: "豆瓣日记", kind: "article", region: "cn", inject_url: "https://www.douban.com/note/create", home_url: "https://www.douban.com/" },
    CatalogEntry { code: "ARTICLE_WEIXIN", name: "微信公众号", kind: "article", region: "cn", inject_url: "https://mp.weixin.qq.com/", home_url: "https://mp.weixin.qq.com/" },
    CatalogEntry { code: "ARTICLE_WORDPRESS", name: "WordPress", kind: "article", region: "intl", inject_url: "https://wordpress.com/wp-admin/new-post.php", home_url: "https://wordpress.com/wp-admin/" },
    CatalogEntry { code: "ARTICLE_BILIBILI", name: "B站专栏", kind: "article", region: "cn", inject_url: "https://member.bilibili.com/article-text/home?newEditor=-1", home_url: "https://www.bilibili.com/" },
    CatalogEntry { code: "ARTICLE_SSPAI", name: "少数派", kind: "article", region: "cn", inject_url: "https://sspai.com/write", home_url: "https://sspai.com/" },
    CatalogEntry { code: "ARTICLE_51CTO", name: "51CTO", kind: "article", region: "cn", inject_url: "https://blog.51cto.com/blogger/publish?old=1", home_url: "https://www.51cto.com/" },
    CatalogEntry { code: "ARTICLE_XUEQIU", name: "雪球", kind: "article", region: "cn", inject_url: "https://mp.xueqiu.com/writeV2?position=pc_home_primary", home_url: "https://xueqiu.com/" },
    CatalogEntry { code: "ARTICLE_WEIBO", name: "微博文章", kind: "article", region: "cn", inject_url: "https://card.weibo.com/article/v5/editor", home_url: "https://weibo.com/" },
    CatalogEntry { code: "ARTICLE_EASTMONEY", name: "东方财富", kind: "article", region: "cn", inject_url: "https://mp.eastmoney.com/collect/pc_article/index.html", home_url: "https://www.eastmoney.com/" },
    CatalogEntry { code: "ARTICLE_SUBSTACK", name: "Substack", kind: "article", region: "intl", inject_url: "https://substack.com/publish/post", home_url: "https://substack.com/" },
    CatalogEntry { code: "ARTICLE_MEDIUM", name: "Medium", kind: "article", region: "intl", inject_url: "https://medium.com/new-story", home_url: "https://medium.com/" },
    CatalogEntry { code: "ARTICLE_OSCHINA", name: "开源中国", kind: "article", region: "cn", inject_url: "https://my.oschina.net/new/blog", home_url: "https://www.oschina.net/" },
    CatalogEntry { code: "ARTICLE_INFOQ", name: "InfoQ", kind: "article", region: "cn", inject_url: "https://xie.infoq.cn/", home_url: "https://www.infoq.cn/" },
    CatalogEntry { code: "ARTICLE_SMZDM", name: "什么值得买", kind: "article", region: "cn", inject_url: "https://zhiyou.smzdm.com/user/article/post", home_url: "https://www.smzdm.com/" },
    CatalogEntry { code: "ARTICLE_WOSHIPM", name: "人人都是产品经理", kind: "article", region: "cn", inject_url: "https://www.woshipm.com/wp-admin/post-new.php", home_url: "https://www.woshipm.com/" },
    CatalogEntry { code: "ARTICLE_GELONGHUI", name: "格隆汇", kind: "article", region: "cn", inject_url: "https://www.gelonghui.com/articleCreate/", home_url: "https://www.gelonghui.com/" },
    CatalogEntry { code: "ARTICLE_JIANKANGJIE", name: "健康界", kind: "article", region: "cn", inject_url: "https://ucenter.cn-healthcare.com/article/revision/newedit", home_url: "https://www.cn-healthcare.com/" },
    CatalogEntry { code: "ARTICLE_KAIDIWANG", name: "凯迪", kind: "article", region: "cn", inject_url: "https://www.9kd.com/create", home_url: "https://www.9kd.com/" },
    CatalogEntry { code: "ARTICLE_AUTOHOME", name: "汽车之家", kind: "article", region: "cn", inject_url: "https://chejiahao.autohome.com.cn/article/post.html", home_url: "https://www.autohome.com.cn/" },
    CatalogEntry { code: "ARTICLE_JIANPIAN", name: "简篇", kind: "article", region: "cn", inject_url: "https://www.jianpian.cn/p/edit", home_url: "https://www.jianpian.cn/" },
    CatalogEntry { code: "ARTICLE_TONGHUASHUN", name: "同花顺", kind: "article", region: "cn", inject_url: "https://t.10jqka.com.cn/newcircle/creation/postAll", home_url: "https://t.10jqka.com.cn/" },
    CatalogEntry { code: "ARTICLE_DONGCHEDI", name: "懂车帝", kind: "article", region: "cn", inject_url: "https://mp.dcdapp.com/profile_v2/publish/article", home_url: "https://mp.dcdapp.com/" },
    CatalogEntry { code: "ARTICLE_ZSXQ", name: "知识星球", kind: "article", region: "cn", inject_url: "https://wx.zsxq.com/", home_url: "https://wx.zsxq.com/" },
    CatalogEntry { code: "ARTICLE_NETEASE", name: "网易号", kind: "article", region: "cn", inject_url: "https://mp.163.com/#/article-publish", home_url: "https://mp.163.com/" },
    CatalogEntry { code: "ARTICLE_SOHU", name: "搜狐号", kind: "article", region: "cn", inject_url: "https://mp.sohu.com/mpfe/v4/contentManagement/news/addarticle", home_url: "https://mp.sohu.com/" },
    CatalogEntry { code: "ARTICLE_DAYUHAO", name: "大鱼号", kind: "article", region: "cn", inject_url: "https://mp.dayu.com/dashboard/article/write", home_url: "https://mp.dayu.com/" },
    CatalogEntry { code: "ARTICLE_DINGDUANHAO", name: "顶端号", kind: "article", region: "cn", inject_url: "https://mp.topnews.cn/#/scriptWrite", home_url: "https://mp.topnews.cn/" },
    CatalogEntry { code: "ARTICLE_KUAICHUANHAO", name: "快传号", kind: "article", region: "cn", inject_url: "https://kuaichuan.360kuai.com/#/console/publish/article", home_url: "https://kuaichuan.360kuai.com/" },
    CatalogEntry { code: "ARTICLE_YIDIANZIXUN", name: "一点资讯", kind: "article", region: "cn", inject_url: "https://mp.yidianzixun.com/#/Writing/articleEditor", home_url: "https://mp.yidianzixun.com/" },
    CatalogEntry { code: "ARTICLE_XARTICLE", name: "X Articles", kind: "article", region: "intl", inject_url: "https://x.com/compose/articles", home_url: "https://x.com/compose/articles" },
    CatalogEntry { code: "PODCAST_QQMUSIC", name: "QQ音乐", kind: "podcast", region: "cn", inject_url: "https://mp.tencentmusic.com/index", home_url: "https://mp.tencentmusic.com/index" },
    CatalogEntry { code: "PODCAST_LIZHI", name: "荔枝", kind: "podcast", region: "cn", inject_url: "https://nj.lizhi.fm/static/newsite/#/index", home_url: "https://nj.lizhi.fm/static/newsite/#/index" },
    CatalogEntry { code: "PODCAST_XIMALAYA", name: "喜马拉雅", kind: "podcast", region: "cn", inject_url: "https://creator.ximalaya.com/anchor/sound-album/sound/single-upload", home_url: "https://creator.ximalaya.com/" },
    CatalogEntry { code: "PODCAST_XIAOYUZHOU", name: "小宇宙", kind: "podcast", region: "cn", inject_url: "https://podcaster.xiaoyuzhoufm.com/dashboard/episodes/new", home_url: "https://podcaster.xiaoyuzhoufm.com/" },
    CatalogEntry { code: "PODCAST_QINGTING", name: "蜻蜓FM", kind: "podcast", region: "cn", inject_url: "https://studio.qingting.fm/album", home_url: "https://studio.qingting.fm/" },
    CatalogEntry { code: "PODCAST_NETEASE", name: "网易云播客", kind: "podcast", region: "cn", inject_url: "https://podcast.music.163.com/web/podcast/upload", home_url: "https://podcast.music.163.com/" },
    CatalogEntry { code: "PODCAST_SPOTIFY", name: "Spotify", kind: "podcast", region: "intl", inject_url: "https://creators.spotify.com/pod/show", home_url: "https://creators.spotify.com/" },
];

